spring.application.name=understand-spring-mail-sender
spring.config.import=classpath:info/configs.properties
logging.level.root[0]=info
logging.level.root[1]=debug
main.prefix.controller=/api/gmail
# Config to java mail sender for SMTP (Simple Mail Transfer Protocol is Protocol type TCP/IP) of Gmail
spring.mail.host=${SMTP_MAIL_HOST}
spring.mail.port=${SMTP_MAIL_PORT}
spring.mail.username=${SMTP_MAIL_USERNAME}
spring.mail.password=${SMTP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true
